# Generated by Django 4.0.2 on 2022-04-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dish', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('value_dish', models.IntegerField(verbose_name='Количество заказанных блюд')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50, verbose_name='Продукт')),
                ('storage', models.IntegerField(verbose_name='Срок хранения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название организации')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(max_length=50, verbose_name='Название типа продукции')),
            ],
            options={
                'verbose_name': 'Тип продукции',
                'verbose_name_plural': 'Тип продукции',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=15, verbose_name='Название говна')),
                ('dt', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('stock', models.ManyToManyField(help_text='Выберите продукт для этой поставки', to='main.Food', verbose_name='Продукты')),
                ('stock_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.status', verbose_name='Статус')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.type', verbose_name='Тип продуктов'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_storage', models.IntegerField(verbose_name='Количество')),
                ('ingredient_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.dish', verbose_name='Выберите блюдо')),
                ('ingredient_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.food', verbose_name='Выберите продукт')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.type', verbose_name='Тип продукции'),
        ),
    ]
